################################################
GET http://localhost:8080/api/mobile/etudiant/10/absences
################################################
GET http://localhost:8080/api/mobile/etudiant/10
################################################
GET http://localhost:8080/api/mobile/vigile/3/historique
################################################
GET http://localhost:8080/api/mobile/vigile/etudiant/ISM2425/DK-0005
#######################################
POST http://localhost:8080/api/mobile/vigile/pointage
Content-Type: application/json 

  {
    "matriculeEtudiant": "ISM2425/DK-0005",
    "vigileId": "3"
  }

################
POST http://localhost:8080/api/auth/login
Content-Type: application/json 

  {
    "email": "admin1@ism.edu.sn",
    "motDePasse": "admin123"
  }
################
GET http://localhost:8080/api/web/absences/annee-active
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjFAaXNtLmVkdS5zbiIsImlhdCI6MTc0OTQzMjUyOCwiZXhwIjoxNzQ5NDM2MTI4fQ.c79QdbiMjkaIPTN2el0_yO9IbmRy7IQm6LXSS0Wujdmjdh9NROA2ofBUOMvSlVDrLxV4ukYmgkd_J1nYJV9BNg
################################################